version: '3.8'

services:
  web:
    build:
      context: ./dir  # Path to the directory containing the Dockerfile
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./dir/index.html:/usr/share/nginx/html/index.html  # Mount the HTML file into the container
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

